In [3]:
import jax
from jax import grad
import jax.numpy as jnp
from jax import jacfwd, jacrev

In [65]:
x_small = jnp.arange(1., 4.)

In [74]:
def sum_cube(x):
  return jnp.prod(jnp.power(x, 3))

In [75]:
jacfwd(jacrev(sum_cube))(x_small)

Array([[1296.,  972.,  648.],
       [ 972.,  324.,  324.],
       [ 648.,  324.,  144.]], dtype=float32)

In [76]:
jacrev(sum_cube)(x_small)

Array([648., 324., 216.], dtype=float32)

In [77]:
jacfwd(sum_cube)(x_small)

Array([648., 324., 216.], dtype=float32)

In [78]:
grad(sum_cube)(x_small)

Array([648., 324., 216.], dtype=float32)

In [79]:
jacrev(jacrev(sum_cube))(x_small)

Array([[1296.,  972.,  648.],
       [ 972.,  324.,  324.],
       [ 648.,  324.,  144.]], dtype=float32)

In [80]:
jacrev(jacfwd(sum_cube))(x_small)

Array([[1296.,  972.,  648.],
       [ 972.,  324.,  324.],
       [ 648.,  324.,  144.]], dtype=float32)

In [81]:
grad(grad(sum_cube))(x_small)

TypeError: Gradient only defined for scalar-output functions. Output had shape: (3,).