`jax.lax.map`과 `jax.vmap`의 비교

In [1]:
import jax
import jax.numpy as jnp

In [2]:
def f(x):
  jax.debug.print("jax.debug.print(x) -> {}", x)
  y = jnp.sin(x)
  jax.debug.print("jax.debug.print(y) -> {}", y)
  return y

xs = jnp.arange(3.)

result = jax.vmap(f)(xs)

jax.debug.print(x) -> 0.0
jax.debug.print(x) -> 1.0
jax.debug.print(x) -> 2.0
jax.debug.print(y) -> 0.0
jax.debug.print(y) -> 0.8414710164070129
jax.debug.print(y) -> 0.9092974662780762


?? : vmap은 vectorization 된다는 확신이 있기 때문에 x, x, x

In [3]:
result = jax.lax.map(f, xs)

jax.debug.print(x) -> 0.0
jax.debug.print(y) -> 0.0
jax.debug.print(x) -> 1.0
jax.debug.print(y) -> 0.8414710164070129
jax.debug.print(x) -> 2.0
jax.debug.print(y) -> 0.9092974662780762


In [4]:
xs = jnp.ones((4,7))

In [8]:
jax.lax.map(lambda _x: _x + 2, xs)

Array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]], dtype=float32)

In [9]:
jax.lax.map(jnp.sum, xs)

Array([7., 7., 7., 7.], dtype=float32)

In [19]:
xs

Array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [16]:
sum_vmap1 = jax.vmap(jnp.sum, in_axes=0)
sum_vmap1(xs)

Array([7., 7., 7., 7.], dtype=float32)

In [23]:
sum_vmap2 = jax.vmap(jnp.sum, in_axes=1)
sum_vmap2(xs)

Array([4., 4., 4., 4., 4., 4., 4.], dtype=float32)