In [1]:
import jax
from jax import random, vmap, make_jaxpr
import jax.numpy as jnp

In [2]:
def get_normal(key):
    result = random.normal(key, (2,))
    jax.debug.print("jax.debug.print(result) -> {result}", result=result)
    return result

In [3]:
key = random.key(42)
subkeys = random.split(key, 3)

In [4]:
get_normal(key)

jax.debug.print(result) -> [-2.169826    0.46480063]


Array([-2.169826  ,  0.46480063], dtype=float32)

In [5]:
jnp.stack([get_normal(subkey) for subkey in subkeys])

jax.debug.print(result) -> [-1.1695957 -0.9732095]
jax.debug.print(result) -> [-0.21746698  0.01024477]
jax.debug.print(result) -> [ 0.1781419  -0.23769319]


Array([[-1.1695957 , -0.9732095 ],
       [-0.21746698,  0.01024477],
       [ 0.1781419 , -0.23769319]], dtype=float32)

In [6]:
vmap_get_normal = vmap(get_normal)

In [7]:
vmap_get_normal(subkeys)

jax.debug.print(result) -> [-1.1695957 -0.9732095]
jax.debug.print(result) -> [-0.21746698  0.01024477]
jax.debug.print(result) -> [ 0.1781419  -0.23769319]


Array([[-1.1695957 , -0.9732095 ],
       [-0.21746698,  0.01024477],
       [ 0.1781419 , -0.23769319]], dtype=float32)

`key`를 `jax.debug.print` 시도하면 안됨

In [8]:
def get_normal2(key):
    result = random.normal(key, (2,))
    jax.debug.print("jax.debug.print(key) -> {key}", key=key)
    #                                         ^^^
    return result

In [9]:
key

Array((), dtype=key<fry>) overlaying:
[ 0 42]

In [10]:
get_normal2(key)

jax.debug_callback failed
Traceback (most recent call last):
  File "/home/helpingstar/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jax/_src/debugging.py", line 84, in debug_callback_impl
    callback(*args)
  File "/home/helpingstar/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jax/_src/debugging.py", line 246, in _flat_callback
    callback(*args, **kwargs)
  File "/home/helpingstar/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jax/_src/debugging.py", line 267, in _format_print_callback
    sys.stdout.write(fmt.format(*args, **kwargs) + "\n")
  File "/home/helpingstar/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jax/_src/prng.py", line 265, in __repr__
    return (f'Array({self.shape}, dtype={self.dtype.name}) overlaying:\n'
  File "/home/helpingstar/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jax/_src/array.py", line 297, in __format__
    return format(self._value, format_spec)
  File "/home/helpingstar/.pyenv/versions/3.10.4/lib/python3.10/site-pa

XlaRuntimeError: INVALID_ARGUMENT: PjRtDevice not found: TFRT_CPU_0